services:
  java-app:
    image: openjdk:17
    container_name: user-service-app
    volumes:
      - ./build/libs:/usr/src/app
    working_dir: /usr/src/app
    command: ["java", "-jar", "UserServiceSpringApi-0.1.jar"]
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL_PG1: jdbc:postgresql://host.docker.internal:5432/comparus1
