logging:
    file:
      name: user-service.log
    level:
      root: WARN
      comparus.service: DEBUG
spring:
  application:
    name: UserServiceSpringApi

dataSources:
  db1: # this database located on local machine. if this connection is unavailable that app ignores it.
    strategy: postgres
    url: "jdbc:postgresql://host.docker.internal:5432/comparus1"
    table: "users"
    user: "postgres"
    password: "root"
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
  db2: # this database located on 'maksim2025/postgres-users-comparus' docker-hub repository.
    strategy: postgres
    url: "jdbc:postgresql://doc-db1:5432/usersdb1"
    table: "users1"
    user: "user1"
    password: "root1"
    mapping:
      id: ldap_id
      username: ldap_username
      name: ldap_name
      surname: ldap_surname
  db3: # this database located on 'maksim2025/users-mysql:1' docker-hub repository.
    strategy: mysql
    url: "jdbc:mysql://doc-db2:3306/userservice"
    table: "user_table"
    user: "myuser"
    password: "my123pass"
    mapping:
      id: user_id
      username: user_username
      name: user_name
      surname: user_surname