logging:
    file:
      name: user-service.log
    level:
      root: WARN
      comparus.service: DEBUG
spring:
  application:
    name: UserServiceSpringApi

dataSources:
  db1:
    strategy: postgres
    url: "jdbc:postgresql://host.docker.internal:5432/comparus1"
    table: "users"
    user: "postgres"
    password: "root"
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
  db2:
    strategy: postgres
    url: "jdbc:postgresql://localhost:5432/comparus2"
    table: "user_table"
    user: "testuser"
    password: "testpass"
    mapping:
      id: ldap_login
      username: ldap_login
      name: name
      surname: surname
