logging:
    file:
      name: user-service.log
#      path:
    level:
      root: WARN
      comparus.service: DEBUG
spring:
  application:
    name: UserServiceSpringApi

dataSources:
  db1:
    strategy: postgres
    url: "jdbc:postgresql://localhost:5432/comparus1"
    table: "users"
    user: "postgres"
    password: "root"
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name
